services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: lapizpapeldb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - default
      - xades-network # Conectar a la red del XAdES

# Conectar a la red externa del XAdES
networks:
  xades-network:
    external: true
